// auth.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.30.0
// source: pkg/proto/auth.proto

package auth

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthValidator_ValidateToken_FullMethodName = "/auth.AuthValidator/ValidateToken"
)

// AuthValidatorClient is the client API for AuthValidator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 1. Servis Tanımı: User Servisinde çalışacak olan doğrulama servisini tanımlarız.
type AuthValidatorClient interface {
	// Gateway, bu metodu çağırarak token'ın geçerliliğini kontrol edecek.
	ValidateToken(ctx context.Context, in *TokenRequest, opts ...grpc.CallOption) (*ValidationResponse, error)
}

type authValidatorClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthValidatorClient(cc grpc.ClientConnInterface) AuthValidatorClient {
	return &authValidatorClient{cc}
}

func (c *authValidatorClient) ValidateToken(ctx context.Context, in *TokenRequest, opts ...grpc.CallOption) (*ValidationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidationResponse)
	err := c.cc.Invoke(ctx, AuthValidator_ValidateToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthValidatorServer is the server API for AuthValidator service.
// All implementations must embed UnimplementedAuthValidatorServer
// for forward compatibility.
//
// 1. Servis Tanımı: User Servisinde çalışacak olan doğrulama servisini tanımlarız.
type AuthValidatorServer interface {
	// Gateway, bu metodu çağırarak token'ın geçerliliğini kontrol edecek.
	ValidateToken(context.Context, *TokenRequest) (*ValidationResponse, error)
	mustEmbedUnimplementedAuthValidatorServer()
}

// UnimplementedAuthValidatorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthValidatorServer struct{}

func (UnimplementedAuthValidatorServer) ValidateToken(context.Context, *TokenRequest) (*ValidationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateToken not implemented")
}
func (UnimplementedAuthValidatorServer) mustEmbedUnimplementedAuthValidatorServer() {}
func (UnimplementedAuthValidatorServer) testEmbeddedByValue()                       {}

// UnsafeAuthValidatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthValidatorServer will
// result in compilation errors.
type UnsafeAuthValidatorServer interface {
	mustEmbedUnimplementedAuthValidatorServer()
}

func RegisterAuthValidatorServer(s grpc.ServiceRegistrar, srv AuthValidatorServer) {
	// If the following call panics, it indicates UnimplementedAuthValidatorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthValidator_ServiceDesc, srv)
}

func _AuthValidator_ValidateToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthValidatorServer).ValidateToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthValidator_ValidateToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthValidatorServer).ValidateToken(ctx, req.(*TokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthValidator_ServiceDesc is the grpc.ServiceDesc for AuthValidator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthValidator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth.AuthValidator",
	HandlerType: (*AuthValidatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ValidateToken",
			Handler:    _AuthValidator_ValidateToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/proto/auth.proto",
}
