// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.30.0
// source: events.proto

package events

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	common "marketplace/pkg/proto/common"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MessageType ve ServiceType enum'ları
type MessageType int32

const (
	MessageType_UNKNOWN_MESSAGE_TYPE  MessageType = 0
	MessageType_USER_CREATED          MessageType = 1
	MessageType_USER_DELETED          MessageType = 2
	MessageType_USER_UPDATED          MessageType = 3
	MessageType_SELLER_APPROVED       MessageType = 4
	MessageType_SELLER_REJECTED       MessageType = 5
	MessageType_PRODUCT_PRICE_UPDATED MessageType = 6
	MessageType_PRODUCT_STOCK_ZERO    MessageType = 7
	MessageType_PRODUCT_DELETED       MessageType = 8
	MessageType_ORDER_CREATED         MessageType = 9
	MessageType_ORDER_UPDATED         MessageType = 10
	MessageType_ORDER_DELETED         MessageType = 11
	MessageType_PAYMENT_CREATED       MessageType = 12
	MessageType_PAYMENT_FAILED        MessageType = 13
	MessageType_PAYMENT_SUCCESSFUL    MessageType = 14
	MessageType_USER_ACTIVATION_EMAIL MessageType = 15 // Diğer mesaj tiplerini buraya ekleyin
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0:  "UNKNOWN_MESSAGE_TYPE",
		1:  "USER_CREATED",
		2:  "USER_DELETED",
		3:  "USER_UPDATED",
		4:  "SELLER_APPROVED",
		5:  "SELLER_REJECTED",
		6:  "PRODUCT_PRICE_UPDATED",
		7:  "PRODUCT_STOCK_ZERO",
		8:  "PRODUCT_DELETED",
		9:  "ORDER_CREATED",
		10: "ORDER_UPDATED",
		11: "ORDER_DELETED",
		12: "PAYMENT_CREATED",
		13: "PAYMENT_FAILED",
		14: "PAYMENT_SUCCESSFUL",
		15: "USER_ACTIVATION_EMAIL",
	}
	MessageType_value = map[string]int32{
		"UNKNOWN_MESSAGE_TYPE":  0,
		"USER_CREATED":          1,
		"USER_DELETED":          2,
		"USER_UPDATED":          3,
		"SELLER_APPROVED":       4,
		"SELLER_REJECTED":       5,
		"PRODUCT_PRICE_UPDATED": 6,
		"PRODUCT_STOCK_ZERO":    7,
		"PRODUCT_DELETED":       8,
		"ORDER_CREATED":         9,
		"ORDER_UPDATED":         10,
		"ORDER_DELETED":         11,
		"PAYMENT_CREATED":       12,
		"PAYMENT_FAILED":        13,
		"PAYMENT_SUCCESSFUL":    14,
		"USER_ACTIVATION_EMAIL": 15,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_events_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_events_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{0}
}

type ServiceType int32

const (
	ServiceType_UNKNOWN_SERVICE      ServiceType = 0
	ServiceType_API_GATEWAY_SERVICE  ServiceType = 1
	ServiceType_USER_SERVICE         ServiceType = 2
	ServiceType_SELLER_SERVICE       ServiceType = 3
	ServiceType_PRODUCT_SERVICE      ServiceType = 4
	ServiceType_ORDER_SERVICE        ServiceType = 5
	ServiceType_RETRY_SERVICE        ServiceType = 6
	ServiceType_BASKET_SERVICE       ServiceType = 7
	ServiceType_PAYMENT_SERVICE      ServiceType = 8
	ServiceType_NOTIFICATION_SERVICE ServiceType = 9 // Diğer servis tiplerini buraya ekleyin
)

// Enum value maps for ServiceType.
var (
	ServiceType_name = map[int32]string{
		0: "UNKNOWN_SERVICE",
		1: "API_GATEWAY_SERVICE",
		2: "USER_SERVICE",
		3: "SELLER_SERVICE",
		4: "PRODUCT_SERVICE",
		5: "ORDER_SERVICE",
		6: "RETRY_SERVICE",
		7: "BASKET_SERVICE",
		8: "PAYMENT_SERVICE",
		9: "NOTIFICATION_SERVICE",
	}
	ServiceType_value = map[string]int32{
		"UNKNOWN_SERVICE":      0,
		"API_GATEWAY_SERVICE":  1,
		"USER_SERVICE":         2,
		"SELLER_SERVICE":       3,
		"PRODUCT_SERVICE":      4,
		"ORDER_SERVICE":        5,
		"RETRY_SERVICE":        6,
		"BASKET_SERVICE":       7,
		"PAYMENT_SERVICE":      8,
		"NOTIFICATION_SERVICE": 9,
	}
)

func (x ServiceType) Enum() *ServiceType {
	p := new(ServiceType)
	*p = x
	return p
}

func (x ServiceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceType) Descriptor() protoreflect.EnumDescriptor {
	return file_events_proto_enumTypes[1].Descriptor()
}

func (ServiceType) Type() protoreflect.EnumType {
	return &file_events_proto_enumTypes[1]
}

func (x ServiceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceType.Descriptor instead.
func (ServiceType) EnumDescriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{1}
}

type Message struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type        MessageType            `protobuf:"varint,2,opt,name=type,proto3,enum=events.MessageType" json:"type,omitempty"`
	Created     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created,proto3" json:"created,omitempty"`
	FromService ServiceType            `protobuf:"varint,4,opt,name=from_service,json=fromService,proto3,enum=events.ServiceType" json:"from_service,omitempty"`
	ToServices  []ServiceType          `protobuf:"varint,5,rep,packed,name=to_services,json=toServices,proto3,enum=events.ServiceType" json:"to_services,omitempty"` // Birden fazla hedef servis
	Priority    int32                  `protobuf:"varint,6,opt,name=priority,proto3" json:"priority,omitempty"`
	Headers     map[string]string      `protobuf:"bytes,7,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Headers for metadata
	Critical    bool                   `protobuf:"varint,8,opt,name=critical,proto3" json:"critical,omitempty"`
	RetryCount  int32                  `protobuf:"varint,9,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	RetryAfter  *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=retry_after,json=retryAfter,proto3" json:"retry_after,omitempty"`
	LastError   string                 `protobuf:"bytes,11,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	// Payload için bir oneof yapısı kullanabiliriz
	//
	// Types that are valid to be assigned to Payload:
	//
	//	*Message_UserCreatedData
	//	*Message_SellerApprovedData
	//	*Message_SellerRejectedData
	//	*Message_ProductPriceUpdatedData
	//	*Message_ProductStockZeroData
	//	*Message_ProductDeletedData
	//	*Message_OrderCreatedData
	//	*Message_PaymentSuccessfulData
	//	*Message_PaymentFailedData
	//	*Message_UserActivationEmailData
	Payload       isMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Message) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_UNKNOWN_MESSAGE_TYPE
}

func (x *Message) GetCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.Created
	}
	return nil
}

func (x *Message) GetFromService() ServiceType {
	if x != nil {
		return x.FromService
	}
	return ServiceType_UNKNOWN_SERVICE
}

func (x *Message) GetToServices() []ServiceType {
	if x != nil {
		return x.ToServices
	}
	return nil
}

func (x *Message) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Message) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *Message) GetCritical() bool {
	if x != nil {
		return x.Critical
	}
	return false
}

func (x *Message) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *Message) GetRetryAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.RetryAfter
	}
	return nil
}

func (x *Message) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *Message) GetPayload() isMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Message) GetUserCreatedData() *UserCreatedData {
	if x != nil {
		if x, ok := x.Payload.(*Message_UserCreatedData); ok {
			return x.UserCreatedData
		}
	}
	return nil
}

func (x *Message) GetSellerApprovedData() *SellerApprovedData {
	if x != nil {
		if x, ok := x.Payload.(*Message_SellerApprovedData); ok {
			return x.SellerApprovedData
		}
	}
	return nil
}

func (x *Message) GetSellerRejectedData() *SellerRejectedData {
	if x != nil {
		if x, ok := x.Payload.(*Message_SellerRejectedData); ok {
			return x.SellerRejectedData
		}
	}
	return nil
}

func (x *Message) GetProductPriceUpdatedData() *ProductPriceUpdatedData {
	if x != nil {
		if x, ok := x.Payload.(*Message_ProductPriceUpdatedData); ok {
			return x.ProductPriceUpdatedData
		}
	}
	return nil
}

func (x *Message) GetProductStockZeroData() *ProductStockZeroData {
	if x != nil {
		if x, ok := x.Payload.(*Message_ProductStockZeroData); ok {
			return x.ProductStockZeroData
		}
	}
	return nil
}

func (x *Message) GetProductDeletedData() *ProductDeletedData {
	if x != nil {
		if x, ok := x.Payload.(*Message_ProductDeletedData); ok {
			return x.ProductDeletedData
		}
	}
	return nil
}

func (x *Message) GetOrderCreatedData() *OrderCreatedData {
	if x != nil {
		if x, ok := x.Payload.(*Message_OrderCreatedData); ok {
			return x.OrderCreatedData
		}
	}
	return nil
}

func (x *Message) GetPaymentSuccessfulData() *PaymentSuccessfulData {
	if x != nil {
		if x, ok := x.Payload.(*Message_PaymentSuccessfulData); ok {
			return x.PaymentSuccessfulData
		}
	}
	return nil
}

func (x *Message) GetPaymentFailedData() *PaymentFailedData {
	if x != nil {
		if x, ok := x.Payload.(*Message_PaymentFailedData); ok {
			return x.PaymentFailedData
		}
	}
	return nil
}

func (x *Message) GetUserActivationEmailData() *UserActivationEmailData {
	if x != nil {
		if x, ok := x.Payload.(*Message_UserActivationEmailData); ok {
			return x.UserActivationEmailData
		}
	}
	return nil
}

type isMessage_Payload interface {
	isMessage_Payload()
}

type Message_UserCreatedData struct {
	UserCreatedData *UserCreatedData `protobuf:"bytes,12,opt,name=user_created_data,json=userCreatedData,proto3,oneof"`
}

type Message_SellerApprovedData struct {
	SellerApprovedData *SellerApprovedData `protobuf:"bytes,13,opt,name=seller_approved_data,json=sellerApprovedData,proto3,oneof"`
}

type Message_SellerRejectedData struct {
	SellerRejectedData *SellerRejectedData `protobuf:"bytes,14,opt,name=seller_rejected_data,json=sellerRejectedData,proto3,oneof"`
}

type Message_ProductPriceUpdatedData struct {
	ProductPriceUpdatedData *ProductPriceUpdatedData `protobuf:"bytes,15,opt,name=product_price_updated_data,json=productPriceUpdatedData,proto3,oneof"`
}

type Message_ProductStockZeroData struct {
	ProductStockZeroData *ProductStockZeroData `protobuf:"bytes,16,opt,name=product_stock_zero_data,json=productStockZeroData,proto3,oneof"`
}

type Message_ProductDeletedData struct {
	ProductDeletedData *ProductDeletedData `protobuf:"bytes,17,opt,name=product_deleted_data,json=productDeletedData,proto3,oneof"`
}

type Message_OrderCreatedData struct {
	OrderCreatedData *OrderCreatedData `protobuf:"bytes,18,opt,name=order_created_data,json=orderCreatedData,proto3,oneof"`
}

type Message_PaymentSuccessfulData struct {
	PaymentSuccessfulData *PaymentSuccessfulData `protobuf:"bytes,19,opt,name=payment_successful_data,json=paymentSuccessfulData,proto3,oneof"`
}

type Message_PaymentFailedData struct {
	PaymentFailedData *PaymentFailedData `protobuf:"bytes,20,opt,name=payment_failed_data,json=paymentFailedData,proto3,oneof"`
}

type Message_UserActivationEmailData struct {
	UserActivationEmailData *UserActivationEmailData `protobuf:"bytes,21,opt,name=user_activation_email_data,json=userActivationEmailData,proto3,oneof"` // Diğer olay tipleri için buraya payload'lar eklenecek
}

func (*Message_UserCreatedData) isMessage_Payload() {}

func (*Message_SellerApprovedData) isMessage_Payload() {}

func (*Message_SellerRejectedData) isMessage_Payload() {}

func (*Message_ProductPriceUpdatedData) isMessage_Payload() {}

func (*Message_ProductStockZeroData) isMessage_Payload() {}

func (*Message_ProductDeletedData) isMessage_Payload() {}

func (*Message_OrderCreatedData) isMessage_Payload() {}

func (*Message_PaymentSuccessfulData) isMessage_Payload() {}

func (*Message_PaymentFailedData) isMessage_Payload() {}

func (*Message_UserActivationEmailData) isMessage_Payload() {}

type UserCreatedData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"` // Diğer ilgili kullanıcı bilgileri
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserCreatedData) Reset() {
	*x = UserCreatedData{}
	mi := &file_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCreatedData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCreatedData) ProtoMessage() {}

func (x *UserCreatedData) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCreatedData.ProtoReflect.Descriptor instead.
func (*UserCreatedData) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{1}
}

func (x *UserCreatedData) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserCreatedData) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserCreatedData) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type UserActivationEmailData struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Username       string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email          string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	ActivationCode string                 `protobuf:"bytes,3,opt,name=activation_code,json=activationCode,proto3" json:"activation_code,omitempty"`
	ActivationId   string                 `protobuf:"bytes,4,opt,name=activation_id,json=activationId,proto3" json:"activation_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UserActivationEmailData) Reset() {
	*x = UserActivationEmailData{}
	mi := &file_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserActivationEmailData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserActivationEmailData) ProtoMessage() {}

func (x *UserActivationEmailData) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserActivationEmailData.ProtoReflect.Descriptor instead.
func (*UserActivationEmailData) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{2}
}

func (x *UserActivationEmailData) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserActivationEmailData) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserActivationEmailData) GetActivationCode() string {
	if x != nil {
		return x.ActivationCode
	}
	return ""
}

func (x *UserActivationEmailData) GetActivationId() string {
	if x != nil {
		return x.ActivationId
	}
	return ""
}

type SellerApprovedData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SellerId      string                 `protobuf:"bytes,1,opt,name=seller_id,json=sellerId,proto3" json:"seller_id,omitempty"`
	ApprovedBy    string                 `protobuf:"bytes,2,opt,name=approved_by,json=approvedBy,proto3" json:"approved_by,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SellerApprovedData) Reset() {
	*x = SellerApprovedData{}
	mi := &file_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SellerApprovedData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SellerApprovedData) ProtoMessage() {}

func (x *SellerApprovedData) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SellerApprovedData.ProtoReflect.Descriptor instead.
func (*SellerApprovedData) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{3}
}

func (x *SellerApprovedData) GetSellerId() string {
	if x != nil {
		return x.SellerId
	}
	return ""
}

func (x *SellerApprovedData) GetApprovedBy() string {
	if x != nil {
		return x.ApprovedBy
	}
	return ""
}

func (x *SellerApprovedData) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type SellerRejectedData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SellerId      string                 `protobuf:"bytes,1,opt,name=seller_id,json=sellerId,proto3" json:"seller_id,omitempty"`
	RejectedBy    string                 `protobuf:"bytes,2,opt,name=rejected_by,json=rejectedBy,proto3" json:"rejected_by,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SellerRejectedData) Reset() {
	*x = SellerRejectedData{}
	mi := &file_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SellerRejectedData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SellerRejectedData) ProtoMessage() {}

func (x *SellerRejectedData) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SellerRejectedData.ProtoReflect.Descriptor instead.
func (*SellerRejectedData) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{4}
}

func (x *SellerRejectedData) GetSellerId() string {
	if x != nil {
		return x.SellerId
	}
	return ""
}

func (x *SellerRejectedData) GetRejectedBy() string {
	if x != nil {
		return x.RejectedBy
	}
	return ""
}

func (x *SellerRejectedData) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *SellerRejectedData) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ProductPriceUpdatedData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Price         float32                `protobuf:"fixed32,2,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductPriceUpdatedData) Reset() {
	*x = ProductPriceUpdatedData{}
	mi := &file_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductPriceUpdatedData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductPriceUpdatedData) ProtoMessage() {}

func (x *ProductPriceUpdatedData) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductPriceUpdatedData.ProtoReflect.Descriptor instead.
func (*ProductPriceUpdatedData) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{5}
}

func (x *ProductPriceUpdatedData) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *ProductPriceUpdatedData) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type ProductStockZeroData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductStockZeroData) Reset() {
	*x = ProductStockZeroData{}
	mi := &file_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductStockZeroData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductStockZeroData) ProtoMessage() {}

func (x *ProductStockZeroData) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductStockZeroData.ProtoReflect.Descriptor instead.
func (*ProductStockZeroData) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{6}
}

func (x *ProductStockZeroData) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

type ProductDeletedData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductDeletedData) Reset() {
	*x = ProductDeletedData{}
	mi := &file_events_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductDeletedData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductDeletedData) ProtoMessage() {}

func (x *ProductDeletedData) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductDeletedData.ProtoReflect.Descriptor instead.
func (*ProductDeletedData) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{7}
}

func (x *ProductDeletedData) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

type OrderCreatedData struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	OrderId       string                  `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        string                  `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TotalPrice    float64                 `protobuf:"fixed64,3,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	Items         []*common.OrderItemData `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderCreatedData) Reset() {
	*x = OrderCreatedData{}
	mi := &file_events_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCreatedData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCreatedData) ProtoMessage() {}

func (x *OrderCreatedData) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCreatedData.ProtoReflect.Descriptor instead.
func (*OrderCreatedData) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{8}
}

func (x *OrderCreatedData) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderCreatedData) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *OrderCreatedData) GetTotalPrice() float64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

func (x *OrderCreatedData) GetItems() []*common.OrderItemData {
	if x != nil {
		return x.Items
	}
	return nil
}

type PaymentSuccessfulData struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OrderId         string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId          string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StripeSessionId string                 `protobuf:"bytes,3,opt,name=stripe_session_id,json=stripeSessionId,proto3" json:"stripe_session_id,omitempty"`
	Amount          float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PaymentSuccessfulData) Reset() {
	*x = PaymentSuccessfulData{}
	mi := &file_events_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentSuccessfulData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentSuccessfulData) ProtoMessage() {}

func (x *PaymentSuccessfulData) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentSuccessfulData.ProtoReflect.Descriptor instead.
func (*PaymentSuccessfulData) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{9}
}

func (x *PaymentSuccessfulData) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *PaymentSuccessfulData) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PaymentSuccessfulData) GetStripeSessionId() string {
	if x != nil {
		return x.StripeSessionId
	}
	return ""
}

func (x *PaymentSuccessfulData) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type PaymentFailedData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	FailureCode   string                 `protobuf:"bytes,4,opt,name=failure_code,json=failureCode,proto3" json:"failure_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentFailedData) Reset() {
	*x = PaymentFailedData{}
	mi := &file_events_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentFailedData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentFailedData) ProtoMessage() {}

func (x *PaymentFailedData) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentFailedData.ProtoReflect.Descriptor instead.
func (*PaymentFailedData) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{10}
}

func (x *PaymentFailedData) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *PaymentFailedData) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PaymentFailedData) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *PaymentFailedData) GetFailureCode() string {
	if x != nil {
		return x.FailureCode
	}
	return ""
}

var File_events_proto protoreflect.FileDescriptor

const file_events_proto_rawDesc = "" +
	"\n" +
	"\fevents.proto\x12\x06events\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\fcommon.proto\"\xd8\n" +
	"\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x04type\x18\x02 \x01(\x0e2\x13.events.MessageTypeR\x04type\x124\n" +
	"\acreated\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\acreated\x126\n" +
	"\ffrom_service\x18\x04 \x01(\x0e2\x13.events.ServiceTypeR\vfromService\x124\n" +
	"\vto_services\x18\x05 \x03(\x0e2\x13.events.ServiceTypeR\n" +
	"toServices\x12\x1a\n" +
	"\bpriority\x18\x06 \x01(\x05R\bpriority\x126\n" +
	"\aheaders\x18\a \x03(\v2\x1c.events.Message.HeadersEntryR\aheaders\x12\x1a\n" +
	"\bcritical\x18\b \x01(\bR\bcritical\x12\x1f\n" +
	"\vretry_count\x18\t \x01(\x05R\n" +
	"retryCount\x12;\n" +
	"\vretry_after\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"retryAfter\x12\x1d\n" +
	"\n" +
	"last_error\x18\v \x01(\tR\tlastError\x12E\n" +
	"\x11user_created_data\x18\f \x01(\v2\x17.events.UserCreatedDataH\x00R\x0fuserCreatedData\x12N\n" +
	"\x14seller_approved_data\x18\r \x01(\v2\x1a.events.SellerApprovedDataH\x00R\x12sellerApprovedData\x12N\n" +
	"\x14seller_rejected_data\x18\x0e \x01(\v2\x1a.events.SellerRejectedDataH\x00R\x12sellerRejectedData\x12^\n" +
	"\x1aproduct_price_updated_data\x18\x0f \x01(\v2\x1f.events.ProductPriceUpdatedDataH\x00R\x17productPriceUpdatedData\x12U\n" +
	"\x17product_stock_zero_data\x18\x10 \x01(\v2\x1c.events.ProductStockZeroDataH\x00R\x14productStockZeroData\x12N\n" +
	"\x14product_deleted_data\x18\x11 \x01(\v2\x1a.events.ProductDeletedDataH\x00R\x12productDeletedData\x12H\n" +
	"\x12order_created_data\x18\x12 \x01(\v2\x18.events.OrderCreatedDataH\x00R\x10orderCreatedData\x12W\n" +
	"\x17payment_successful_data\x18\x13 \x01(\v2\x1d.events.PaymentSuccessfulDataH\x00R\x15paymentSuccessfulData\x12K\n" +
	"\x13payment_failed_data\x18\x14 \x01(\v2\x19.events.PaymentFailedDataH\x00R\x11paymentFailedData\x12^\n" +
	"\x1auser_activation_email_data\x18\x15 \x01(\v2\x1f.events.UserActivationEmailDataH\x00R\x17userActivationEmailData\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\t\n" +
	"\apayload\"\\\n" +
	"\x0fUserCreatedData\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\"\x99\x01\n" +
	"\x17UserActivationEmailData\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12'\n" +
	"\x0factivation_code\x18\x03 \x01(\tR\x0eactivationCode\x12#\n" +
	"\ractivation_id\x18\x04 \x01(\tR\factivationId\"k\n" +
	"\x12SellerApprovedData\x12\x1b\n" +
	"\tseller_id\x18\x01 \x01(\tR\bsellerId\x12\x1f\n" +
	"\vapproved_by\x18\x02 \x01(\tR\n" +
	"approvedBy\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\"\x83\x01\n" +
	"\x12SellerRejectedData\x12\x1b\n" +
	"\tseller_id\x18\x01 \x01(\tR\bsellerId\x12\x1f\n" +
	"\vrejected_by\x18\x02 \x01(\tR\n" +
	"rejectedBy\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\"N\n" +
	"\x17ProductPriceUpdatedData\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x02R\x05price\"5\n" +
	"\x14ProductStockZeroData\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\"3\n" +
	"\x12ProductDeletedData\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\"\x94\x01\n" +
	"\x10OrderCreatedData\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1f\n" +
	"\vtotal_price\x18\x03 \x01(\x01R\n" +
	"totalPrice\x12+\n" +
	"\x05items\x18\x04 \x03(\v2\x15.common.OrderItemDataR\x05items\"\x8f\x01\n" +
	"\x15PaymentSuccessfulData\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12*\n" +
	"\x11stripe_session_id\x18\x03 \x01(\tR\x0fstripeSessionId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\"\x8f\x01\n" +
	"\x11PaymentFailedData\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12!\n" +
	"\ffailure_code\x18\x04 \x01(\tR\vfailureCode*\xe4\x02\n" +
	"\vMessageType\x12\x18\n" +
	"\x14UNKNOWN_MESSAGE_TYPE\x10\x00\x12\x10\n" +
	"\fUSER_CREATED\x10\x01\x12\x10\n" +
	"\fUSER_DELETED\x10\x02\x12\x10\n" +
	"\fUSER_UPDATED\x10\x03\x12\x13\n" +
	"\x0fSELLER_APPROVED\x10\x04\x12\x13\n" +
	"\x0fSELLER_REJECTED\x10\x05\x12\x19\n" +
	"\x15PRODUCT_PRICE_UPDATED\x10\x06\x12\x16\n" +
	"\x12PRODUCT_STOCK_ZERO\x10\a\x12\x13\n" +
	"\x0fPRODUCT_DELETED\x10\b\x12\x11\n" +
	"\rORDER_CREATED\x10\t\x12\x11\n" +
	"\rORDER_UPDATED\x10\n" +
	"\x12\x11\n" +
	"\rORDER_DELETED\x10\v\x12\x13\n" +
	"\x0fPAYMENT_CREATED\x10\f\x12\x12\n" +
	"\x0ePAYMENT_FAILED\x10\r\x12\x16\n" +
	"\x12PAYMENT_SUCCESSFUL\x10\x0e\x12\x19\n" +
	"\x15USER_ACTIVATION_EMAIL\x10\x0f*\xdf\x01\n" +
	"\vServiceType\x12\x13\n" +
	"\x0fUNKNOWN_SERVICE\x10\x00\x12\x17\n" +
	"\x13API_GATEWAY_SERVICE\x10\x01\x12\x10\n" +
	"\fUSER_SERVICE\x10\x02\x12\x12\n" +
	"\x0eSELLER_SERVICE\x10\x03\x12\x13\n" +
	"\x0fPRODUCT_SERVICE\x10\x04\x12\x11\n" +
	"\rORDER_SERVICE\x10\x05\x12\x11\n" +
	"\rRETRY_SERVICE\x10\x06\x12\x12\n" +
	"\x0eBASKET_SERVICE\x10\a\x12\x13\n" +
	"\x0fPAYMENT_SERVICE\x10\b\x12\x18\n" +
	"\x14NOTIFICATION_SERVICE\x10\tB\x1eZ\x1cmarketplace/pkg/proto/eventsb\x06proto3"

var (
	file_events_proto_rawDescOnce sync.Once
	file_events_proto_rawDescData []byte
)

func file_events_proto_rawDescGZIP() []byte {
	file_events_proto_rawDescOnce.Do(func() {
		file_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_events_proto_rawDesc), len(file_events_proto_rawDesc)))
	})
	return file_events_proto_rawDescData
}

var file_events_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_events_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_events_proto_goTypes = []any{
	(MessageType)(0),                // 0: events.MessageType
	(ServiceType)(0),                // 1: events.ServiceType
	(*Message)(nil),                 // 2: events.Message
	(*UserCreatedData)(nil),         // 3: events.UserCreatedData
	(*UserActivationEmailData)(nil), // 4: events.UserActivationEmailData
	(*SellerApprovedData)(nil),      // 5: events.SellerApprovedData
	(*SellerRejectedData)(nil),      // 6: events.SellerRejectedData
	(*ProductPriceUpdatedData)(nil), // 7: events.ProductPriceUpdatedData
	(*ProductStockZeroData)(nil),    // 8: events.ProductStockZeroData
	(*ProductDeletedData)(nil),      // 9: events.ProductDeletedData
	(*OrderCreatedData)(nil),        // 10: events.OrderCreatedData
	(*PaymentSuccessfulData)(nil),   // 11: events.PaymentSuccessfulData
	(*PaymentFailedData)(nil),       // 12: events.PaymentFailedData
	nil,                             // 13: events.Message.HeadersEntry
	(*timestamppb.Timestamp)(nil),   // 14: google.protobuf.Timestamp
	(*common.OrderItemData)(nil),    // 15: common.OrderItemData
}
var file_events_proto_depIdxs = []int32{
	0,  // 0: events.Message.type:type_name -> events.MessageType
	14, // 1: events.Message.created:type_name -> google.protobuf.Timestamp
	1,  // 2: events.Message.from_service:type_name -> events.ServiceType
	1,  // 3: events.Message.to_services:type_name -> events.ServiceType
	13, // 4: events.Message.headers:type_name -> events.Message.HeadersEntry
	14, // 5: events.Message.retry_after:type_name -> google.protobuf.Timestamp
	3,  // 6: events.Message.user_created_data:type_name -> events.UserCreatedData
	5,  // 7: events.Message.seller_approved_data:type_name -> events.SellerApprovedData
	6,  // 8: events.Message.seller_rejected_data:type_name -> events.SellerRejectedData
	7,  // 9: events.Message.product_price_updated_data:type_name -> events.ProductPriceUpdatedData
	8,  // 10: events.Message.product_stock_zero_data:type_name -> events.ProductStockZeroData
	9,  // 11: events.Message.product_deleted_data:type_name -> events.ProductDeletedData
	10, // 12: events.Message.order_created_data:type_name -> events.OrderCreatedData
	11, // 13: events.Message.payment_successful_data:type_name -> events.PaymentSuccessfulData
	12, // 14: events.Message.payment_failed_data:type_name -> events.PaymentFailedData
	4,  // 15: events.Message.user_activation_email_data:type_name -> events.UserActivationEmailData
	15, // 16: events.OrderCreatedData.items:type_name -> common.OrderItemData
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_events_proto_init() }
func file_events_proto_init() {
	if File_events_proto != nil {
		return
	}
	file_events_proto_msgTypes[0].OneofWrappers = []any{
		(*Message_UserCreatedData)(nil),
		(*Message_SellerApprovedData)(nil),
		(*Message_SellerRejectedData)(nil),
		(*Message_ProductPriceUpdatedData)(nil),
		(*Message_ProductStockZeroData)(nil),
		(*Message_ProductDeletedData)(nil),
		(*Message_OrderCreatedData)(nil),
		(*Message_PaymentSuccessfulData)(nil),
		(*Message_PaymentFailedData)(nil),
		(*Message_UserActivationEmailData)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_events_proto_rawDesc), len(file_events_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_events_proto_goTypes,
		DependencyIndexes: file_events_proto_depIdxs,
		EnumInfos:         file_events_proto_enumTypes,
		MessageInfos:      file_events_proto_msgTypes,
	}.Build()
	File_events_proto = out.File
	file_events_proto_goTypes = nil
	file_events_proto_depIdxs = nil
}
