// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.30.0
// source: events.proto

package events

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MessageType ve ServiceType enum'ları
type MessageType int32

const (
	MessageType_UNKNOWN_MESSAGE_TYPE MessageType = 0
	MessageType_USER_CREATED         MessageType = 1
	MessageType_USER_DELETED         MessageType = 2
	MessageType_USER_UPDATED         MessageType = 3
	MessageType_SELLER_APPROVED      MessageType = 4
	MessageType_SELLER_REJECTED      MessageType = 5 // Diğer mesaj tiplerini buraya ekleyin
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "UNKNOWN_MESSAGE_TYPE",
		1: "USER_CREATED",
		2: "USER_DELETED",
		3: "USER_UPDATED",
		4: "SELLER_APPROVED",
		5: "SELLER_REJECTED",
	}
	MessageType_value = map[string]int32{
		"UNKNOWN_MESSAGE_TYPE": 0,
		"USER_CREATED":         1,
		"USER_DELETED":         2,
		"USER_UPDATED":         3,
		"SELLER_APPROVED":      4,
		"SELLER_REJECTED":      5,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_events_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_events_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{0}
}

type ServiceType int32

const (
	ServiceType_UNKNOWN_SERVICE     ServiceType = 0
	ServiceType_API_GATEWAY_SERVICE ServiceType = 1
	ServiceType_USER_SERVICE        ServiceType = 2
	ServiceType_SELLER_SERVICE      ServiceType = 3
	ServiceType_PRODUCT_SERVICE     ServiceType = 4
	ServiceType_ORDER_SERVICE       ServiceType = 5
	ServiceType_RETRY_SERVICE       ServiceType = 6 // Diğer servis tiplerini buraya ekleyin
)

// Enum value maps for ServiceType.
var (
	ServiceType_name = map[int32]string{
		0: "UNKNOWN_SERVICE",
		1: "API_GATEWAY_SERVICE",
		2: "USER_SERVICE",
		3: "SELLER_SERVICE",
		4: "PRODUCT_SERVICE",
		5: "ORDER_SERVICE",
		6: "RETRY_SERVICE",
	}
	ServiceType_value = map[string]int32{
		"UNKNOWN_SERVICE":     0,
		"API_GATEWAY_SERVICE": 1,
		"USER_SERVICE":        2,
		"SELLER_SERVICE":      3,
		"PRODUCT_SERVICE":     4,
		"ORDER_SERVICE":       5,
		"RETRY_SERVICE":       6,
	}
)

func (x ServiceType) Enum() *ServiceType {
	p := new(ServiceType)
	*p = x
	return p
}

func (x ServiceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceType) Descriptor() protoreflect.EnumDescriptor {
	return file_events_proto_enumTypes[1].Descriptor()
}

func (ServiceType) Type() protoreflect.EnumType {
	return &file_events_proto_enumTypes[1]
}

func (x ServiceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceType.Descriptor instead.
func (ServiceType) EnumDescriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{1}
}

type Message struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type        MessageType            `protobuf:"varint,2,opt,name=type,proto3,enum=events.MessageType" json:"type,omitempty"`
	Created     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created,proto3" json:"created,omitempty"`
	FromService ServiceType            `protobuf:"varint,4,opt,name=from_service,json=fromService,proto3,enum=events.ServiceType" json:"from_service,omitempty"`
	ToServices  []ServiceType          `protobuf:"varint,5,rep,packed,name=to_services,json=toServices,proto3,enum=events.ServiceType" json:"to_services,omitempty"` // Birden fazla hedef servis
	Priority    int32                  `protobuf:"varint,6,opt,name=priority,proto3" json:"priority,omitempty"`
	Headers     map[string]string      `protobuf:"bytes,7,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Headers for metadata
	Critical    bool                   `protobuf:"varint,8,opt,name=critical,proto3" json:"critical,omitempty"`
	RetryCount  int32                  `protobuf:"varint,9,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	// Payload için bir oneof yapısı kullanabiliriz
	//
	// Types that are valid to be assigned to Payload:
	//
	//	*Message_UserCreatedData
	//	*Message_SellerApprovedData
	//	*Message_SellerRejectedData
	Payload       isMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Message) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_UNKNOWN_MESSAGE_TYPE
}

func (x *Message) GetCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.Created
	}
	return nil
}

func (x *Message) GetFromService() ServiceType {
	if x != nil {
		return x.FromService
	}
	return ServiceType_UNKNOWN_SERVICE
}

func (x *Message) GetToServices() []ServiceType {
	if x != nil {
		return x.ToServices
	}
	return nil
}

func (x *Message) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Message) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *Message) GetCritical() bool {
	if x != nil {
		return x.Critical
	}
	return false
}

func (x *Message) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *Message) GetPayload() isMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Message) GetUserCreatedData() *UserCreatedData {
	if x != nil {
		if x, ok := x.Payload.(*Message_UserCreatedData); ok {
			return x.UserCreatedData
		}
	}
	return nil
}

func (x *Message) GetSellerApprovedData() *SellerApprovedData {
	if x != nil {
		if x, ok := x.Payload.(*Message_SellerApprovedData); ok {
			return x.SellerApprovedData
		}
	}
	return nil
}

func (x *Message) GetSellerRejectedData() *SellerRejectedData {
	if x != nil {
		if x, ok := x.Payload.(*Message_SellerRejectedData); ok {
			return x.SellerRejectedData
		}
	}
	return nil
}

type isMessage_Payload interface {
	isMessage_Payload()
}

type Message_UserCreatedData struct {
	UserCreatedData *UserCreatedData `protobuf:"bytes,10,opt,name=user_created_data,json=userCreatedData,proto3,oneof"`
}

type Message_SellerApprovedData struct {
	SellerApprovedData *SellerApprovedData `protobuf:"bytes,11,opt,name=seller_approved_data,json=sellerApprovedData,proto3,oneof"`
}

type Message_SellerRejectedData struct {
	SellerRejectedData *SellerRejectedData `protobuf:"bytes,12,opt,name=seller_rejected_data,json=sellerRejectedData,proto3,oneof"` // Diğer olay tipleri için buraya payload'lar eklenecek
}

func (*Message_UserCreatedData) isMessage_Payload() {}

func (*Message_SellerApprovedData) isMessage_Payload() {}

func (*Message_SellerRejectedData) isMessage_Payload() {}

type UserCreatedData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"` // Diğer ilgili kullanıcı bilgileri
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserCreatedData) Reset() {
	*x = UserCreatedData{}
	mi := &file_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCreatedData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCreatedData) ProtoMessage() {}

func (x *UserCreatedData) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCreatedData.ProtoReflect.Descriptor instead.
func (*UserCreatedData) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{1}
}

func (x *UserCreatedData) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserCreatedData) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserCreatedData) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type SellerApprovedData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SellerId      string                 `protobuf:"bytes,1,opt,name=seller_id,json=sellerId,proto3" json:"seller_id,omitempty"`
	ApprovedBy    string                 `protobuf:"bytes,2,opt,name=approved_by,json=approvedBy,proto3" json:"approved_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SellerApprovedData) Reset() {
	*x = SellerApprovedData{}
	mi := &file_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SellerApprovedData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SellerApprovedData) ProtoMessage() {}

func (x *SellerApprovedData) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SellerApprovedData.ProtoReflect.Descriptor instead.
func (*SellerApprovedData) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{2}
}

func (x *SellerApprovedData) GetSellerId() string {
	if x != nil {
		return x.SellerId
	}
	return ""
}

func (x *SellerApprovedData) GetApprovedBy() string {
	if x != nil {
		return x.ApprovedBy
	}
	return ""
}

type SellerRejectedData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SellerId      string                 `protobuf:"bytes,1,opt,name=seller_id,json=sellerId,proto3" json:"seller_id,omitempty"`
	RejectedBy    string                 `protobuf:"bytes,2,opt,name=rejected_by,json=rejectedBy,proto3" json:"rejected_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SellerRejectedData) Reset() {
	*x = SellerRejectedData{}
	mi := &file_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SellerRejectedData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SellerRejectedData) ProtoMessage() {}

func (x *SellerRejectedData) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SellerRejectedData.ProtoReflect.Descriptor instead.
func (*SellerRejectedData) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{3}
}

func (x *SellerRejectedData) GetSellerId() string {
	if x != nil {
		return x.SellerId
	}
	return ""
}

func (x *SellerRejectedData) GetRejectedBy() string {
	if x != nil {
		return x.RejectedBy
	}
	return ""
}

var File_events_proto protoreflect.FileDescriptor

const file_events_proto_rawDesc = "" +
	"\n" +
	"\fevents.proto\x12\x06events\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa5\x05\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x04type\x18\x02 \x01(\x0e2\x13.events.MessageTypeR\x04type\x124\n" +
	"\acreated\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\acreated\x126\n" +
	"\ffrom_service\x18\x04 \x01(\x0e2\x13.events.ServiceTypeR\vfromService\x124\n" +
	"\vto_services\x18\x05 \x03(\x0e2\x13.events.ServiceTypeR\n" +
	"toServices\x12\x1a\n" +
	"\bpriority\x18\x06 \x01(\x05R\bpriority\x126\n" +
	"\aheaders\x18\a \x03(\v2\x1c.events.Message.HeadersEntryR\aheaders\x12\x1a\n" +
	"\bcritical\x18\b \x01(\bR\bcritical\x12\x1f\n" +
	"\vretry_count\x18\t \x01(\x05R\n" +
	"retryCount\x12E\n" +
	"\x11user_created_data\x18\n" +
	" \x01(\v2\x17.events.UserCreatedDataH\x00R\x0fuserCreatedData\x12N\n" +
	"\x14seller_approved_data\x18\v \x01(\v2\x1a.events.SellerApprovedDataH\x00R\x12sellerApprovedData\x12N\n" +
	"\x14seller_rejected_data\x18\f \x01(\v2\x1a.events.SellerRejectedDataH\x00R\x12sellerRejectedData\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\t\n" +
	"\apayload\"\\\n" +
	"\x0fUserCreatedData\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\"R\n" +
	"\x12SellerApprovedData\x12\x1b\n" +
	"\tseller_id\x18\x01 \x01(\tR\bsellerId\x12\x1f\n" +
	"\vapproved_by\x18\x02 \x01(\tR\n" +
	"approvedBy\"R\n" +
	"\x12SellerRejectedData\x12\x1b\n" +
	"\tseller_id\x18\x01 \x01(\tR\bsellerId\x12\x1f\n" +
	"\vrejected_by\x18\x02 \x01(\tR\n" +
	"rejectedBy*\x87\x01\n" +
	"\vMessageType\x12\x18\n" +
	"\x14UNKNOWN_MESSAGE_TYPE\x10\x00\x12\x10\n" +
	"\fUSER_CREATED\x10\x01\x12\x10\n" +
	"\fUSER_DELETED\x10\x02\x12\x10\n" +
	"\fUSER_UPDATED\x10\x03\x12\x13\n" +
	"\x0fSELLER_APPROVED\x10\x04\x12\x13\n" +
	"\x0fSELLER_REJECTED\x10\x05*\x9c\x01\n" +
	"\vServiceType\x12\x13\n" +
	"\x0fUNKNOWN_SERVICE\x10\x00\x12\x17\n" +
	"\x13API_GATEWAY_SERVICE\x10\x01\x12\x10\n" +
	"\fUSER_SERVICE\x10\x02\x12\x12\n" +
	"\x0eSELLER_SERVICE\x10\x03\x12\x13\n" +
	"\x0fPRODUCT_SERVICE\x10\x04\x12\x11\n" +
	"\rORDER_SERVICE\x10\x05\x12\x11\n" +
	"\rRETRY_SERVICE\x10\x06B\n" +
	"Z\b./eventsb\x06proto3"

var (
	file_events_proto_rawDescOnce sync.Once
	file_events_proto_rawDescData []byte
)

func file_events_proto_rawDescGZIP() []byte {
	file_events_proto_rawDescOnce.Do(func() {
		file_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_events_proto_rawDesc), len(file_events_proto_rawDesc)))
	})
	return file_events_proto_rawDescData
}

var file_events_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_events_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_events_proto_goTypes = []any{
	(MessageType)(0),              // 0: events.MessageType
	(ServiceType)(0),              // 1: events.ServiceType
	(*Message)(nil),               // 2: events.Message
	(*UserCreatedData)(nil),       // 3: events.UserCreatedData
	(*SellerApprovedData)(nil),    // 4: events.SellerApprovedData
	(*SellerRejectedData)(nil),    // 5: events.SellerRejectedData
	nil,                           // 6: events.Message.HeadersEntry
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_events_proto_depIdxs = []int32{
	0, // 0: events.Message.type:type_name -> events.MessageType
	7, // 1: events.Message.created:type_name -> google.protobuf.Timestamp
	1, // 2: events.Message.from_service:type_name -> events.ServiceType
	1, // 3: events.Message.to_services:type_name -> events.ServiceType
	6, // 4: events.Message.headers:type_name -> events.Message.HeadersEntry
	3, // 5: events.Message.user_created_data:type_name -> events.UserCreatedData
	4, // 6: events.Message.seller_approved_data:type_name -> events.SellerApprovedData
	5, // 7: events.Message.seller_rejected_data:type_name -> events.SellerRejectedData
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_events_proto_init() }
func file_events_proto_init() {
	if File_events_proto != nil {
		return
	}
	file_events_proto_msgTypes[0].OneofWrappers = []any{
		(*Message_UserCreatedData)(nil),
		(*Message_SellerApprovedData)(nil),
		(*Message_SellerRejectedData)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_events_proto_rawDesc), len(file_events_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_events_proto_goTypes,
		DependencyIndexes: file_events_proto_depIdxs,
		EnumInfos:         file_events_proto_enumTypes,
		MessageInfos:      file_events_proto_msgTypes,
	}.Build()
	File_events_proto = out.File
	file_events_proto_goTypes = nil
	file_events_proto_depIdxs = nil
}
